[package]
name = "tin/better-brainrot"
version = "0.1.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
Red = "red-blox/red@2.3.2"
Janitor = "howmanysmall/janitor@1.18.3"
Signal = "stravant/goodsignal@0.3.0"
Timer = "sleitnick/timer@1.1.2"
